# Generated by Django 4.2.3 on 2023-07-18 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upscale', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Upscale',
        ),
    ]
