# Generated by Django 4.2.3 on 2023-07-18 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upscale', '0002_rename_mymodel_upscale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upscale',
            name='output_image',
        ),
    ]
