# Generated by Django 4.2.3 on 2023-07-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upscale', '0003_remove_upscale_output_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='upscale',
            name='name',
            field=models.CharField(default='img', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upscale',
            name='output_image',
            field=models.ImageField(default='out', upload_to='output_images/'),
            preserve_default=False,
        ),
    ]
