# Generated by Django 4.2.3 on 2023-07-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upscale', '0005_remove_upscale_output_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upscale',
            name='name',
        ),
        migrations.AlterField(
            model_name='upscale',
            name='input_image',
            field=models.ImageField(upload_to='input_images'),
        ),
    ]
