# Generated by Django 4.2.3 on 2023-07-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upscale', '0002_upscale_output_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpscaleOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_image', models.ImageField(upload_to='result_images/images/output/')),
            ],
        ),
        migrations.RemoveField(
            model_name='upscale',
            name='output_image',
        ),
    ]
